### ISSUE TITLE
breaks angular's cold observable logic

### ISSUE THREAD

**Issue by ribizli** [davguij/angular-http-cache#2]
by default angular's `Http` doesn't sends the request until a subscription happens (cold observable). reading your code it seems you start the request immediately.
use rather the `new Observable(subrciber => {})` construct.

**Comment by davguij** [comment]
You're quite right. I'll give it a spin when through the week.
Thanks!

**Comment by davguij** [comment]
Solved by [release 1.2.0](https://github.com/davguij/angular-http-cache/releases/tag/1.2.0).
